[font]
size = 14.0

[font.bold]
family = "Mononoki Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Mononoki Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Mononoki Nerd Font"
style = "Italic"

[font.normal]
family = "Mononoki Nerd Font"
style = "Regular"

[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"

[window]
decorations = "none"
opacity = 1.0
startup_mode = "Maximized"

[window.position]
x = 0
y = 0
